---
title: "Create Order Figure"
author: Anonymized
#author: "Poornima Belavadi, Nils Plettenberg, Johannes Nakayama, André Calero Valdez"
date: "3/12/2020"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    code_folding: hide
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
library(here)
library(ggpubr)
source(here("R", "our_theme.R"))
theme_set(theme_bw() + my_theme)
```


```{r}
plot_list <- list()
title_list <- c(
  expression(1^{st}~"order"),
  expression(2^{nd}~"order"),
  expression(3^{rd}~"order"),
  expression(4^{th}~"order")
)
level_list <- c(4, 16, 64, 256)
for (n in 1:4) {
  df <- data.frame(id = 1:level_list[n])
  tmp_plot <- gghilbertstrings::gghilbertplot(df, id, add_curve = TRUE, alpha = 0, curve_color = "white") +
    coord_fixed() +
    labs(title = title_list[n]) +
    theme(
    plot.background = element_rect(fill = "grey50", color = "grey50"),
    plot.title = element_text(color = "white", hjust = 0.5),
    plot.subtitle = element_text(color = "white"),
    plot.margin = margin(15, 15, 15, 15),
    plot.caption = element_text(color = "white"),
    panel.background = element_blank(), #element_rect(fill = "grey30", color = "grey50"),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none",
    axis.title = element_blank(),
    panel.border = element_blank(),
    axis.text = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )  
  plot_list[[n]] <- tmp_plot
}
ggarrange(plotlist = plot_list) +
  theme(plot.background = element_rect(fill = "grey50", color = "transparent"))
ggsave(here("output", "hilbert_iterations.pdf"), width = 5, height = 5, dpi = 500)
```


